// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5QDB5-EZncGVHdix8UKQLHbHP2AcscxI',
    appId: '1:975273801425:web:af6125a4fe17347eea77f0',
    messagingSenderId: '975273801425',
    projectId: 'last-8ab70',
    authDomain: 'last-8ab70.firebaseapp.com',
    storageBucket: 'last-8ab70.firebasestorage.app',
    measurementId: 'G-BPRZFTXQDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh99W6qir0s1C1RBCACrzV1WLj-xAtWK4',
    appId: '1:975273801425:android:64abfa9e79d35d14ea77f0',
    messagingSenderId: '975273801425',
    projectId: 'last-8ab70',
    storageBucket: 'last-8ab70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJnn3_qp2UI0CeCQ3bkfgG7z6kyBr2-kw',
    appId: '1:975273801425:ios:d40dbae06911a88cea77f0',
    messagingSenderId: '975273801425',
    projectId: 'last-8ab70',
    storageBucket: 'last-8ab70.firebasestorage.app',
    iosBundleId: 'com.example.last',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJnn3_qp2UI0CeCQ3bkfgG7z6kyBr2-kw',
    appId: '1:975273801425:ios:d40dbae06911a88cea77f0',
    messagingSenderId: '975273801425',
    projectId: 'last-8ab70',
    storageBucket: 'last-8ab70.firebasestorage.app',
    iosBundleId: 'com.example.last',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5QDB5-EZncGVHdix8UKQLHbHP2AcscxI',
    appId: '1:975273801425:web:be75405a60816d49ea77f0',
    messagingSenderId: '975273801425',
    projectId: 'last-8ab70',
    authDomain: 'last-8ab70.firebaseapp.com',
    storageBucket: 'last-8ab70.firebasestorage.app',
    measurementId: 'G-JPZKJN5S22',
  );
}
